### ISSUE TITLE
Unhandled promise rejection 

### ISSUE THREAD

**Issue by taniadaniela** [Poincare/persistgraphql#6]
I'm having this issue when trying to execute: 
```extractgql q.grapql test.json
(node:28632) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 

GraphQLError: Syntax Error GraphQL (1:1) Unexpected <EOF>

1:
   ^
```
I'm using extractgql": "^0.2.1" with node@6.9.1 and graphql 0.9.0 on Mac OS

**Comment by Poincare** [comment]
Could you describe what kind of file structure you have as well as some of the queries associated with the project? What arguments were passed to the CLI tool?

**Comment by taniadaniela** [comment]
node_modules/extractgql/bin/extractgql src
on a nodejs app using apollo server and graphql

**Comment by taniadaniela** [comment]
was a syntax error on my graphql file, fixed now.

**Comment by chollier** [comment]
@taniadaniela how did you spot the error?
